-- Migrate static product data to database with proper UUIDs
-- This populates the products table with all the products from the static data file

INSERT INTO public.products (
  name, category, price, description, specifications, features, images, rating, review_count, stock, featured
) VALUES
-- Chef Knives
('Elite Damascus Chef Knife', 'chef', 299.99, 'Professional-grade Damascus steel chef knife with exceptional sharpness and edge retention. Perfect for all kitchen tasks from chopping vegetables to slicing meat.', '{"bladeLength": "8 inches (20cm)", "totalLength": "13 inches (33cm)", "bladeMaterial": "Damascus Steel (67 layers)", "handleMaterial": "Ebony Wood with Brass Bolster", "weight": "7.2 oz (204g)", "origin": "Japan"}', '["67-layer Damascus steel construction", "Razor-sharp 15° edge angle", "Ergonomic ebony handle", "Brass bolster for balance", "Corrosion resistant"]', '["/src/assets/chef-damascus.jpg"]', 4.9, 234, 15, true),
('Classic German Chef Knife', 'chef', 179.99, 'Traditional German forged chef knife with full tang construction and triple-riveted handle. Built to last generations.', '{"bladeLength": "8 inches (20cm)", "totalLength": "12.5 inches (32cm)", "bladeMaterial": "German Stainless Steel", "handleMaterial": "Black Polymer with Steel Rivets", "weight": "8.1 oz (230g)", "origin": "Germany"}', '["Full tang construction", "Triple-riveted handle", "Ice-hardened blade", "Dishwasher safe", "Lifetime warranty"]', '["/src/assets/chef-german.jpg"]', 4.7, 189, 8, false),
('Carbon Steel Gyuto', 'chef', 249.99, 'Traditional Japanese Gyuto knife in blue carbon steel. Develops a beautiful patina over time and takes an incredibly sharp edge.', '{"bladeLength": "9 inches (24cm)", "totalLength": "14 inches (36cm)", "bladeMaterial": "Blue Carbon Steel #2", "handleMaterial": "Magnolia Wood", "weight": "6.8 oz (193g)", "origin": "Japan"}', '["Blue carbon steel core", "Hand-forged construction", "Traditional wa-handle", "Develops patina", "Ultra-thin blade geometry"]', '["/images/chef-gyuto-1.jpg", "/images/chef-gyuto-2.jpg"]', 4.8, 156, 12, true),

-- Paring Knives
('Precision Paring Knife', 'paring', 89.99, 'Nimble paring knife for detailed work. Perfect for peeling, trimming, and intricate cutting tasks.', '{"bladeLength": "3.5 inches (9cm)", "totalLength": "7 inches (18cm)", "bladeMaterial": "High Carbon Stainless Steel", "handleMaterial": "Stabilized Wood", "weight": "2.1 oz (60g)", "origin": "USA"}', '["Surgical-grade steel", "Ergonomic grip", "Stain resistant", "Easy to sharpen", "Lightweight design"]', '["/src/assets/paring-precision.jpg"]', 4.6, 78, 20, false),
('Classic Paring Set', 'paring', 129.99, 'Set of three paring knives: straight, curved, and serrated. Complete solution for all small cutting tasks.', '{"bladeLength": "3 inches (7.5cm)", "totalLength": "6.5 inches (17cm)", "bladeMaterial": "German Stainless Steel", "handleMaterial": "Black Polymer", "weight": "1.8 oz each (51g)", "origin": "Germany"}', '["Set of 3 knives", "Multiple blade styles", "Matching handles", "Storage block included", "Dishwasher safe"]', '["/images/paring-set-1.jpg", "/images/paring-set-2.jpg"]', 4.5, 92, 6, false),

-- Santoku Knives
('Hollowed Santoku Knife', 'santoku', 189.99, 'Japanese-style santoku with hollowed edge to prevent sticking. Excellent for vegetables, fish, and meat.', '{"bladeLength": "7 inches (18cm)", "totalLength": "11.5 inches (29cm)", "bladeMaterial": "VG-10 Steel Core", "handleMaterial": "Pakkawood", "weight": "5.9 oz (167g)", "origin": "Japan"}', '["Hollowed edge design", "VG-10 steel core", "Granton blade", "Non-slip handle", "Versatile cutting"]', '["/src/assets/santoku-hollowed.jpg"]', 4.8, 143, 10, true),
('Traditional Santoku', 'santoku', 159.99, 'Classic Japanese santoku knife with traditional profile. All-purpose kitchen knife for the home cook.', '{"bladeLength": "6.5 inches (16.5cm)", "totalLength": "11 inches (28cm)", "bladeMaterial": "AUS-10 Stainless Steel", "handleMaterial": "Traditional Wood", "weight": "5.2 oz (147g)", "origin": "Japan"}', '["Traditional Japanese profile", "AUS-10 steel", "Comfortable grip", "Easy maintenance", "Versatile design"]', '["/images/santoku-traditional-1.jpg", "/images/santoku-traditional-2.jpg"]', 4.6, 87, 14, false),

-- Cleaver Knives
('Heavy Duty Cleaver', 'cleaver', 149.99, 'Robust meat cleaver for heavy-duty kitchen tasks. Perfect for breaking down large cuts of meat and poultry.', '{"bladeLength": "7 inches (18cm)", "totalLength": "12 inches (30cm)", "bladeMaterial": "440C Stainless Steel", "handleMaterial": "Textured Polymer", "weight": "12.5 oz (354g)", "origin": "China"}', '["Heavy-duty construction", "Full tang design", "Non-slip grip", "Thick blade spine", "Easy to clean"]', '["/src/assets/cleaver-heavy.jpg"]', 4.4, 56, 7, false),
('Chinese Vegetable Cleaver', 'cleaver', 119.99, 'Thin Chinese-style cleaver perfect for vegetables and light chopping tasks. Surprisingly versatile.', '{"bladeLength": "8 inches (20cm)", "totalLength": "13 inches (33cm)", "bladeMaterial": "Carbon Steel", "handleMaterial": "Hardwood", "weight": "7.8 oz (221g)", "origin": "China"}', '["Thin blade profile", "Carbon steel edge", "Traditional design", "Lightweight feel", "Develops patina"]', '["/images/cleaver-chinese-1.jpg", "/images/cleaver-chinese-2.jpg"]', 4.7, 73, 9, false),

-- Pocket/Folding Knives
('Tactical EDC Folding Knife', 'pocket', 129.99, 'Everyday carry folding knife with assisted opening and tactical features. Perfect for utility tasks.', '{"bladeLength": "3.5 inches (9cm)", "totalLength": "8 inches open (20cm)", "bladeMaterial": "S30V Steel", "handleMaterial": "G10 Composite", "weight": "4.2 oz (119g)", "origin": "USA"}', '["Assisted opening", "Pocket clip", "Liner lock", "Thumb studs", "Glass breaker tip"]', '["/src/assets/pocket-tactical.jpg"]', 4.8, 198, 18, true),
('Classic Gentlemans Folder', 'pocket', 89.99, 'Traditional gentlemans folding knife with elegant design. Perfect for everyday carry.', '{"bladeLength": "3 inches (7.5cm)", "totalLength": "7 inches open (18cm)", "bladeMaterial": "154CM Steel", "handleMaterial": "Bone", "weight": "3.1 oz (88g)", "origin": "USA"}', '["Traditional design", "Bone handle scales", "Slip joint mechanism", "Polished finish", "Collector quality"]', '["/images/pocket-gentleman-1.jpg", "/images/pocket-gentleman-2.jpg"]', 4.5, 67, 11, false),
('Utility Multi-tool Knife', 'pocket', 159.99, 'Multi-function pocket knife with various tools. Essential for outdoor activities and daily tasks.', '{"bladeLength": "3.25 inches (8cm)", "totalLength": "4.5 inches closed (11cm)", "bladeMaterial": "420HC Steel", "handleMaterial": "Stainless Steel", "weight": "5.8 oz (164g)", "origin": "Switzerland"}', '["15 built-in tools", "Locking blade", "Can opener", "Screwdrivers", "Lifetime warranty"]', '["/images/pocket-multi-1.jpg", "/images/pocket-multi-2.jpg"]', 4.6, 134, 22, false),

-- Hunting Knives
('Professional Skinning Knife', 'hunting', 179.99, 'Curved skinning knife designed for efficient field dressing and processing of game.', '{"bladeLength": "4 inches (10cm)", "totalLength": "8.5 inches (21cm)", "bladeMaterial": "D2 Tool Steel", "handleMaterial": "Micarta", "weight": "4.8 oz (136g)", "origin": "USA"}', '["Curved skinning blade", "D2 tool steel", "Full tang construction", "Leather sheath included", "Field-tested design"]', '["/images/hunting-skinning-1.jpg", "/images/hunting-skinning-2.jpg"]', 4.7, 89, 5, false),
('Drop Point Hunter', 'hunting', 149.99, 'Versatile drop point hunting knife for general field work and processing tasks.', '{"bladeLength": "4.5 inches (11cm)", "totalLength": "9 inches (23cm)", "bladeMaterial": "1084 Carbon Steel", "handleMaterial": "Antler", "weight": "5.4 oz (153g)", "origin": "USA"}', '["Drop point design", "Carbon steel blade", "Antler handle", "Hand forged", "Custom leather sheath"]', '["/src/assets/hunting-drop.jpg"]', 4.8, 76, 13, true),
('Gut Hook Hunter', 'hunting', 134.99, 'Specialized hunting knife with integrated gut hook for field dressing game.', '{"bladeLength": "4 inches (10cm)", "totalLength": "8.75 inches (22cm)", "bladeMaterial": "440C Stainless Steel", "handleMaterial": "Rubber Overmold", "weight": "5.1 oz (144g)", "origin": "USA"}', '["Integrated gut hook", "Stainless steel blade", "Non-slip grip", "Corrosion resistant", "Nylon sheath included"]', '["/images/hunting-gut-1.jpg", "/images/hunting-gut-2.jpg"]', 4.4, 52, 8, false),

-- Fixed Blade Knives
('Bushcraft Survival Knife', 'fixed-blade', 199.99, 'Heavy-duty survival knife built for bushcraft and outdoor adventures. Full tang construction with fire starter.', '{"bladeLength": "5 inches (13cm)", "totalLength": "10 inches (25cm)", "bladeMaterial": "1095 High Carbon Steel", "handleMaterial": "Canvas Micarta", "weight": "8.2 oz (232g)", "origin": "USA"}', '["Full tang construction", "Fire steel striker", "Scandi grind", "Kydex sheath", "Paracord lanyard"]', '["/src/assets/fixed-bushcraft.jpg"]', 4.9, 167, 16, true),
('Combat Tactical Knife', 'fixed-blade', 249.99, 'Military-inspired tactical knife with aggressive design and premium materials.', '{"bladeLength": "6 inches (15cm)", "totalLength": "11 inches (28cm)", "bladeMaterial": "CPM-3V Steel", "handleMaterial": "G10 Composite", "weight": "9.8 oz (278g)", "origin": "USA"}', '["Tactical design", "CPM-3V steel", "Aggressive serrations", "MOLLE compatible sheath", "Mil-spec coating"]', '["/images/fixed-tactical-1.jpg", "/images/fixed-tactical-2.jpg"]', 4.6, 94, 4, false),
('Classic Bowie Knife', 'fixed-blade', 189.99, 'Traditional Bowie knife with classic design and modern materials. A timeless piece.', '{"bladeLength": "7 inches (18cm)", "totalLength": "12 inches (30cm)", "bladeMaterial": "5160 Spring Steel", "handleMaterial": "Stag Horn", "weight": "10.5 oz (298g)", "origin": "USA"}', '["Classic Bowie profile", "Spring steel blade", "Stag horn handle", "Brass guard", "Hand-stitched sheath"]', '["/images/fixed-bowie-1.jpg", "/images/fixed-bowie-2.jpg"]', 4.7, 78, 19, false),
('Fillet Fishing Knife', 'fixed-blade', 79.99, 'Flexible fillet knife perfect for cleaning fish. Thin blade for precise cuts.', '{"bladeLength": "6 inches (15cm)", "totalLength": "11 inches (28cm)", "bladeMaterial": "420J2 Stainless Steel", "handleMaterial": "Non-slip Rubber", "weight": "3.9 oz (110g)", "origin": "Finland"}', '["Flexible blade", "Corrosion resistant", "Ergonomic handle", "Easy to clean", "Floating design"]', '["/images/fixed-fillet-1.jpg", "/images/fixed-fillet-2.jpg"]', 4.3, 41, 12, false),
('Utility Work Knife', 'fixed-blade', 69.99, 'Sturdy work knife for everyday utility tasks. Built to handle tough jobs.', '{"bladeLength": "4 inches (10cm)", "totalLength": "8.5 inches (21cm)", "bladeMaterial": "8Cr13MoV Steel", "handleMaterial": "TPR Rubber", "weight": "4.6 oz (130g)", "origin": "China"}', '["Utility blade shape", "Stain resistant steel", "Comfortable grip", "Belt clip", "Value pricing"]', '["/images/fixed-utility-1.jpg", "/images/fixed-utility-2.jpg"]', 4.1, 28, 25, false);