// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnamgzvipuvzahbirjoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuYW1nenZpcHV2emFoYmlyam9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NzI4MzAsImV4cCI6MjA3MTM0ODgzMH0.VC4KIVF2rpbz7ZLJ3yZesYc5OVBl0HRQDlTl9Z3TgkU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});